# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'SocketChapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocketChapter
  pod 'CocoaAsyncSocket'
  pod 'SULogger'
  pod 'Masonry'

end
